#!/usr/bin/env bash
HELLO_FROM_PATH=$(dirname $(realpath "$0"))
export PYTHONPATH=$HELLO_FROM_PATH
export PYTHON_BIN=$HELLO_FROM_PATH/penv/bin/python
mkdir -p ttyrecs/$USER
TS=$(date -u +%s)
export RUST_BACKTRACE=1
export HOME=$(pwd)

if [[ -f "$HELLO_FROM_PATH/ovhttyrec/bin/ttyrec" ]]; then
    TTYREC="$HELLO_FROM_PATH/ovhttyrec/bin/ttyrec"
else
    TTYREC="$HELLO_FROM_PATH/ovh-ttyrec/ttyrec"
fi

$TTYREC -f ttyrecs/$USER/${TS}_${DB_USER_ID}.ttyrec "$HELLO_FROM_PATH/build/bin/nethack" -u $@
