#!/usr/bin/env bash
cd /home/herden/projects/nethackathon2024/
export PYTHONPATH=/home/herden/projects/nethackathon2024
export PYTHON_BIN=/home/herden/projects/nethackathon2024/penv/bin/python
mkdir -p ttyrecs/$USER
TS=$(date -u +%s)
export RUST_BACKTRACE=1
export HOME=$(pwd)
ovhttyrec/bin/ttyrec -f ttyrecs/$USER/${TS}_${DB_USER_ID}.ttyrec build/bin/nethack -u $@
