language = "C"
includes = ["hack.h"]
pragma_once = true
style = "tag"
after_includes = "#define obj struct obj"
trailer = "#undef obj"
# [parse]
# parse_deps = true
# include = [ "nethack-rs" ]
[export]
# exclude = [ "obj" ]
