/* This source file is generated by 'makedefs'.  Do not edit. */

#if !defined(CROSSCOMPILE) || !defined(CROSSCOMPILE_TARGET)
#define BUILD_DATE "Sun Apr  9 01:35:41 2023"
#define BUILD_TIME (1680996941UL)

#define VERSION_NUMBER 0x03070020UL
#define VERSION_FEATURES 0x00060040UL
#define IGNORED_FEATURES 0x18080000UL
#define VERSION_SANITY1 0x211cc17dUL
#define VERSION_SANITY2 0x278e28980UL
#define VERSION_SANITY3 0x00028000UL

#define VERSION_STRING "3.7.0-32"
#define VERSION_ID \
 "Unix NetHack Version 3.7.0-32 Work-in-progress - last build Sun Apr  9 01:35:41 2023."
#define COPYRIGHT_BANNER_C \
 "         Version 3.7.0-32 Unix Work-in-progress, built Apr  9 01:35:41 2023."
#define NETHACK_GIT_SHA "3f1344e8f392e97bd4d76e5d00d816c518fbb2fe"
#define NETHACK_GIT_BRANCH "master"
#endif /* !CROSSCOMPILE || !CROSSCOMPILE_TARGET */

